### ISSUE TITLE
Proposal to change how contour operations work internally (re: ContourOperations for pen types i.e. HyperBezierContour, SpiroContour, QuadContour…)

### ISSUE THREAD

**Issue by MatthewBlanchard** [mfeq/glifparser#19]
I've been considering adding Hyperbezier as a contour operation, and I think a few things should probably happen to contour operations before that's the case.

Contour operations should work more similarly to tools in implementation. They should be in a Box<dyn ContourOperation> and use dynamic dispatch to call the ContourOperation implementations instead of a match statement. If need be this can happen post-load of MFEKGlif because I'm not sure how Box\<dyn\> works with serialization.

There should be a separation of 'contour operations' like PAP and VWS which take a bezier and output a set of contours and things like Spiro and Hyperbezier which take in a set of points -> output a set of beziers. You should be able to apply operations like PAP and VWS to hyperbezier just like any other contour.

**Comment by ctrlcctrlv** [comment]
### To answer your query:

> If need be this can happen post-load of MFEKGlif because I'm not sure how Box<dyn> works with serialization.

No— I don't think so. When we convert an MFEKGlif (the type) to a Glif type we can load things into the Glif's `<lib>` based on, not only ContourOperations, but other MFEK-only elements of MFEKGlif.

MFEKGlif should not need to have something called on it after it's created to support serialization of its special attributes into Glif…ultimately I want to get to a place where converting MFEKGlif to Glif and back is a totally lossless roundtrip, with the Glif `<lib>` getting packed and unpacked by the `From` and `Into` implementations.

MFEKglif (the application) is meant to be very interoperable, and I wouldn't want MFEKglif to create a new Hyperbezier standard, we must use @cmyr's standard (`org.linebender.hyperbezier-version`, `org.linebender.hyperbezier-point`, `org.linebender.hyperbezier-control`). For Spiro we can come up with our own standard, but we should probably make it similar… `org.MFEK.spiro-(version|point)`. 

Luckily Serde can work with boxed traits. I have not used it before but considered it already for serialization of `Box<dyn Tool>` (I wanted to see if I could make it so when you close a glyph, and reopen it, I could restore the tool you had open when you closed MFEKglif): https://github.com/dtolnay/typetag

All you do is tag the trait with `#[typetag::serde(tag = "contour_ops_type")]` then tag the impl's as opposed to tagging the enum variants with `#[serde(bound = "T: MyTrait")]`.

### But onto the bigger issue—

You're leaving the project (you said) so I don't understand where this is coming from. Will send more along these lines privately.

**Comment by ctrlcctrlv** [comment]
Oh, for my own memory, this is heavily related to https://github.com/MFEK/glifparser.rlib/commit/123a7c44913d4902b5a422343fc6d1272ddecead ( `trait ManageContourOperations`) and https://github.com/MFEK/glifparser.rlib/commit/02abdde48c5877522f118d4088e0b18989bba792 (`impl<PD> Into<Contour<PD>> for MFEKContour<PD>`, `trait (Upgrade|Downgrade)Contour`), both of which are part of the drive to make `Glif→MFEKGlif→Glif` a clean roundtrip with no data loss, which would be enormously beneficial.

**Comment by ctrlcctrlv** [comment]
we did this
