### ISSUE TITLE
Contours can contain mixed types

### ISSUE THREAD

**Issue by madig** [mfeq/glifparser#20]
https://github.com/MFEK/glifparser.rlib/blob/e443ccbd4d33c73654c342b268e36e44b62f6b71/src/outline.rs#L25

I have seen mixed outlines before, somewhere. ufo2ft would convert cubics to quadratics for TTF compilation and leave the existing quadratics alone. Just a random thought :)

**Comment by ctrlcctrlv** [comment]
Interesting, thanks. I think you may have seen them because of a FontForge bug. MFEKglif is _very_ anti-mixed contour, for good reason, but there's no reason glifparser needs to panic instead of converting.

**Comment by ctrlcctrlv** [comment]
https://github.com/MFEK/glifparser.rlib/commit/32df74975c3b6238f3ddf822f639fa6f324dbc7d should have closed
