### ISSUE TITLE
`<advance>` attributes can be floats

### ISSUE THREAD

**Issue by ianh** [mfeq/glifparser#54]
I'm trying to load glyphs from the Inter typeface, which have floating-point advance values.  The spec [here](https://unifiedfontobject.org/versions/ufo3/glyphs/glif/#advance) seems to allow this, but glifparser rejects these files.  See e.g. [Q_.glif.txt](https://github.com/MFEK/glifparser.rlib/files/9737535/Q_.glif.txt).

**Comment by ctrlcctrlv** [comment]
I'll patch this but the fix is truncation.
